# Generated by Django 4.1.3 on 2023-05-29 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stock', models.CharField(default='', max_length=50)),
                ('total_price', models.FloatField(default=0.0)),
                ('type', models.CharField(choices=[('in', 'In'), ('out', 'Out')], default='', max_length=20)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('owner', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description_color', models.CharField(default='', max_length=120)),
                ('buy_rate', models.DecimalField(decimal_places=2, max_digits=120)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_mobile_products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
