# Generated by Django 4.1.3 on 2023-06-02 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0009_alter_transaction_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='total_price',
        ),
        migrations.AddField(
            model_name='transaction',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='transaction',
            name='remark',
            field=models.CharField(default='', max_length=120),
        ),
    ]
