# Generated by Django 4.1.3 on 2023-01-26 11:54

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile',
            field=models.ImageField(default='products/default.png', upload_to=users.models.upload_to, verbose_name='Image'),
        ),
    ]
