# Generated by Django 4.1.3 on 2023-05-12 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_createuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createuser',
            name='password',
        ),
    ]
