# Generated by Django 4.1.3 on 2023-05-22 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_createuser_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreateUser',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_mobile_user',
            field=models.BooleanField(default=False),
        ),
    ]
