# Generated by Django 4.1.3 on 2024-05-11 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import store.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=65)),
                ('description', models.CharField(max_length=220)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('owner', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer', models.CharField(default='', max_length=50)),
                ('buyer_location', models.CharField(default='', max_length=50)),
                ('buyer_phone', models.CharField(default='', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('declined', 'Declined'), ('approved', 'Approved'), ('processing', 'Processing'), ('incomplete', 'Incomplete'), ('complete', 'Complete'), ('bulk', 'Bulk')], default='', max_length=20)),
                ('ref', models.CharField(default='', max_length=50)),
                ('price_paid', models.FloatField(default=0.0)),
                ('total_price', models.FloatField(default=0.0)),
                ('type', models.CharField(choices=[('invoice', 'Invoice'), ('receipt', 'Receipt'), ('order', 'Order')], default='', max_length=20)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('owner', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(default='', max_length=200)),
                ('country', models.CharField(default='', max_length=200)),
                ('phone_number', models.CharField(default='', max_length=200)),
                ('industry', models.CharField(blank=True, default='', max_length=200)),
                ('contactName', models.CharField(default='', max_length=200)),
                ('email', models.EmailField(blank=True, default='', max_length=200)),
                ('additional_information', models.CharField(blank=True, default='', max_length=200)),
                ('additional_files', models.CharField(blank=True, default='', max_length=200)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=65)),
                ('address', models.CharField(max_length=220)),
            ],
        ),
        migrations.CreateModel(
            name='StoreActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=65)),
                ('description_color', models.CharField(default='', max_length=65)),
                ('price', models.DecimalField(decimal_places=2, max_digits=65)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=60)),
                ('stock', models.PositiveIntegerField(default='')),
                ('status', models.CharField(choices=[('in_stock', 'In Stock'), ('out_of_stock', 'Out of Stock')], default='', max_length=65)),
                ('supplier', models.CharField(default='', max_length=50)),
                ('image', models.ImageField(default='products/default.png', upload_to=store.models.upload_to, verbose_name='Image')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Expiry Date')),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='store.category')),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='store.OrderProducts', to='store.product'),
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default='', max_length=65)),
                ('status', models.CharField(choices=[('delivered', 'delivered'), ('pending', 'pending')], default='', max_length=20)),
                ('reciept', models.CharField(default='', max_length=65)),
                ('courier_name', models.CharField(default='', max_length=65)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('order', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='store.order')),
            ],
        ),
        migrations.CreateModel(
            name='Damages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=220)),
                ('damages', models.PositiveIntegerField(default=0)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('owner', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='damages', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=65, unique=True)),
                ('address', models.CharField(default='', max_length=220)),
                ('mobile_number', models.CharField(default='', max_length=220)),
                ('email', models.EmailField(default='', max_length=220)),
                ('tax_id', models.CharField(default='', max_length=220)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('owner', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='buyers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
