# Generated by Django 4.1.3 on 2023-01-24 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0003_category_owner'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductQuantity',
            new_name='OrderProducts',
        ),
        migrations.RenameField(
            model_name='orderproducts',
            old_name='product_quantity',
            new_name='quantity',
        ),
        migrations.AddField(
            model_name='order',
            name='owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
