# Generated by Django 3.1.13 on 2022-09-03 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220813_1707'),
        ('store', '0005_auto_20200722_0405'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('name', models.CharField(max_length=120, unique=True)),
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.user')),
                ('price', models.CharField(max_length=220)),
                ('product_id', models.IntegerField(max_length=220)),
                ('total', models.IntegerField(max_length=220)),
                ('qty', models.IntegerField(max_length=220)),
                ('shop_id', models.IntegerField(max_length=220)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('name', models.CharField(max_length=120, unique=True)),
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.user')),
                ('location', models.CharField(max_length=120, unique=True)),
                ('user_id', models.IntegerField(max_length=220)),
                ('user_name', models.IntegerField(max_length=220)),
                ('product_id', models.IntegerField(max_length=220)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
