# Generated by Django 3.1.13 on 2022-09-07 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20220907_2121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='contact',
            new_name='category_id',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='status',
            new_name='images',
        ),
        migrations.AddField(
            model_name='product',
            name='label',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.CharField(default='', max_length=120),
        ),
    ]
