# Generated by Django 4.1.3 on 2023-05-07 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='label_size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sortno',
        ),
    ]
