# Generated by Django 4.1.1 on 2022-09-12 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20220907_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='additional_files',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='supplier',
            name='additional_information',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='supplier',
            name='companyName',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='supplier',
            name='contactName',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='supplier',
            name='country',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='supplier',
            name='email',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='supplier',
            name='industry',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='supplier',
            name='phone_number',
            field=models.CharField(default='', max_length=200),
        ),
    ]
