# Generated by Django 4.1.3 on 2023-05-07 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_product_label_size_remove_product_sku_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='buyer_location',
            field=models.CharField(default='', max_length=50),
        ),
    ]
