# Generated by Django 4.1.1 on 2022-09-22 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_supplier_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='user',
        ),
        migrations.AddField(
            model_name='buyer',
            name='email',
            field=models.CharField(default='', max_length=220),
        ),
        migrations.AddField(
            model_name='buyer',
            name='mobile_number',
            field=models.CharField(default='', max_length=220),
        ),
        migrations.AddField(
            model_name='buyer',
            name='tax_id',
            field=models.CharField(default='', max_length=220),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='address',
            field=models.CharField(default='', max_length=220),
        ),
    ]
