# Generated by Django 4.1.3 on 2023-05-11 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_product_owner_mobileproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mobileproduct',
            old_name='description_color',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='mobileproduct',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='mobileproduct',
            name='status',
        ),
    ]
