# Generated by Django 4.1.3 on 2023-05-19 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_rename_description_color_mobileproduct_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='receipt',
        ),
    ]
