# Generated by Django 4.1.1 on 2022-10-05 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_product_status'),
        ('store', '0014_alter_delivery_order'),
    ]

    operations = [
    ]
