# Generated by Django 4.1.3 on 2023-06-10 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_damages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default='', max_length=10),
        ),
    ]
