# Generated by Django 4.1.1 on 2022-10-06 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_buyer_email_alter_delivery_order_and_more'),
        ('store', '0015_merge_0010_product_status_0014_alter_delivery_order'),
    ]

    operations = [
    ]
