# Generated by Django 4.1.1 on 2022-10-06 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_merge_20221006_1141'),
        ('store', '0018_alter_order_status_alter_product_status'),
    ]

    operations = [
    ]
