# Generated by Django 4.1.3 on 2024-01-29 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='buyer_phone',
            field=models.CharField(default='', max_length=50),
        ),
    ]
