# Generated by Django 4.1.3 on 2024-01-29 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_logentry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogEntry',
        ),
    ]
