# Generated by Django 4.1.1 on 2022-10-06 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_remove_order_color_remove_order_design_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='reciept',
            new_name='receipt',
        ),
    ]
