# Generated by Django 4.1.1 on 2022-10-07 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_merge_20221006_1232'),
        ('store', '0021_category_alter_product_category_id'),
        ('store', '0023_rename_reciept_order_receipt'),
    ]

    operations = [
    ]
