# Generated by Django 4.1.3 on 2024-01-29 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_alter_category_name'),
        ('store', '0023_storeactivity'),
    ]

    operations = [
    ]
