# Generated by Django 4.1.3 on 2024-02-05 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_merge_0022_alter_category_name_0023_storeactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price_paid',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('declined', 'Declined'), ('approved', 'Approved'), ('processing', 'Processing'), ('incomplete', 'Incomplete'), ('complete', 'Complete'), ('bulk', 'Bulk')], default='', max_length=20),
        ),
    ]
