# Generated by Django 4.1.1 on 2022-10-07 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_merge_20221007_0033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category_id',
            new_name='category',
        ),
    ]
