# Generated by Django 4.1.3 on 2024-02-11 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_order_price_paid_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost_rice',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=120),
        ),
    ]
