# Generated by Django 4.1.3 on 2024-02-11 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_product_cost_rice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='cost_rice',
            new_name='cost_price',
        ),
    ]
