# Generated by Django 3.1.13 on 2022-10-19 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_auto_20221019_0357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='productquantity',
            name='extra_sauce',
        ),
        migrations.AddField(
            model_name='productquantity',
            name='product_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
