# Generated by Django 3.1.13 on 2022-10-21 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_auto_20221019_0359'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('invoice', 'Invoice'), ('order', 'Order')], default='', max_length=20),
        ),
    ]
