# Generated by Django 3.1.13 on 2022-10-30 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_auto_20221028_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('invoice', 'Invoice'), ('order', 'Order')], default='invoice', max_length=20),
        ),
    ]
