# Generated by Django 3.1.13 on 2022-10-30 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_auto_20221030_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('invoice', 'Invoice'), ('order', 'Order')], default='', max_length=20),
        ),
    ]
