# Generated by Django 4.1.3 on 2023-06-02 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0008_remove_transaction_products_transaction_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile.product'),
        ),
    ]
