# Generated by Django 4.1.3 on 2023-10-11 14:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mobile', '0013_alter_product_stock_alter_transaction_current_stock_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='mProduct',
        ),
    ]
