# Generated by Django 4.1.3 on 2024-02-13 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0014_rename_product_mproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damages',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
