# Generated by Django 4.1.3 on 2024-04-18 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0016_alter_damages_owner_alter_mproduct_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mproduct',
            name='name',
            field=models.CharField(max_length=120),
        ),
    ]
