# Generated by Django 4.1.3 on 2023-01-16 12:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_postcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='customuser',
            name='company_name',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='customuser',
            name='contact',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='customuser',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(default='', max_length=120),
        ),
    ]
