# Generated by Django 4.1.1 on 2022-10-07 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_name'),
        ('users', '0004_user_location_user_phone_number'),
    ]

    operations = [
    ]
