# Generated by Django 3.1.13 on 2022-11-24 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20221124_0959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='location',
            new_name='city',
        ),
        migrations.AddField(
            model_name='user',
            name='postcode',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='user',
            name='region',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='user',
            name='streetAddress',
            field=models.CharField(default='', max_length=120),
        ),
    ]
