# Generated by Django 4.1.3 on 2023-05-12 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customuser_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=120)),
                ('last_name', models.CharField(default='', max_length=120)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('contact', models.CharField(default='', max_length=120)),
                ('password', models.CharField(default='', max_length=8)),
            ],
        ),
    ]
