# Generated by Django 4.1.3 on 2023-05-13 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_createuser_password'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CreateUser',
            new_name='mobileCustomer',
        ),
    ]
