# Generated by Django 4.1.3 on 2023-05-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_rename_createuser_mobilecustomer'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilecustomer',
            name='password',
            field=models.CharField(default='', max_length=8),
        ),
    ]
