# Generated by Django 4.1.3 on 2023-05-15 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_mobilecustomer_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobilecustomer',
            name='password',
        ),
    ]
